learningLog/urls.py
# Mapping a URL
# Users request pages by entering URLs into a browser and clicking links, so
# we’ll need to decide what URLs are needed. The home page URL is first:
# it’s the base URL people use to access the project. At the moment the base
# URL, http: // localhost: 8000 /, returns the default Django site that lets us know
# the project was set up correctly. We’ll change this by mapping the base URL
# to Learning Log’s home page.


# The first two imports, import a module and a function to manage URLs for the admin site.
from django.contrib import admin
from django.urls import path, include

# urlpatterns is a variable, which includes sets of URLs from the app in the project
urlpatterns = [
    # The below includes the module admin.site.urls, which defines all the URLs that can be requested from the admin site.
    path('admin/', admin.site.urls),
    
    # Including users app
    path("users/", include("users.urls")),
    
    # To include the URLs for learningLogs. Make sure to import 'include'.
    path("", include("learningLogs.urls"))
]

# We now need to make a second urls.py in the learningLogs folder.

learningLogs/urls.py
"""Defines URL patterns for learningLogs"""
# Made after editing urls.py in learningLog

# We add a docstring at the start so we know which urls.py we are working in.

# We import the path function, which is needed when mapping URLs to views
from django.urls import path
# Importing the views module, the dot tells python to import the views.py module from the same directory as the current urls.py module.
from . import views

# The variable appName helps django distinguish this urls.py file from files of the same name in other apps within the project.
# app_name is specific code and can't be title cased
app_name = "learningLogs"
# The variable urlpatterns in this module is a list of individual pages that can requested from the learningLogs app.
urlpatterns = [
    # Home page
    # The actual URL pattern is a call to the path() function, which takes
    # three arguments. The first argument is a string that helps Django route
    # the current request properly. Django receives the requested URL and tries
    # to route the request to a view. It does this by searching all the URL patterns
    # we’ve defined to find one that matches the current request. Django ignores
    # the base URL for the project (http://localhost:8000 /), so the empty string
    # ('') matches the base URL. Any other URL won’t match this pattern, and
    # Django will return an error page if the URL requested doesn’t match any
    # existing URL patterns.
    # The second argument in path() specifies which function to call
    # in views.py. When a requested URL matches the pattern we’re defining,
    # Django calls the index() function from views.py(we’ll write this view function
    # in the next section). The third argument provides the name index for
    # this URL pattern so we can refer to it in other code sections. Whenever we
    # want to provide a link to the home page, we’ll use this name instead of writing
    # out a URL.
    path("", views.index, name="index"),
    # Page that shows all topics
    path("topics/", views.topics, name="topics"),
    # Detail page for a single topic
    
    # First part of string tells django to for URLs that have the word topics after the base url.
    # Second part, the int part, matches an integer between two forward slashes and store the integer value in an argument called topicId. We'll use the value of topicId to get the correct topic inside the function
    path("topics/<int:topic_id>/", views.topic, name="topic"),
    
    # Page for adding a new topic
    path("newTopic/", views.newTopic, name="newTopic"),
    # On to views.py
    
    # Page for adding a new entry
    path("newEntry/<int:topic_id>/", views.newEntry, name="newEntry"),
    # On to views.py
    
    # Page for editing an entry
    path("editEntry/<int:entry_id>/", views.editEntry, name="editEntry"),
    # On to views.py
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

# Import the views module from 'users', which we need because we're writing our own view for the registration page.
from . import views

# Creating a new app name so django can differentiate it from learninglogs
app_name = "users"
urlpatterns = [
    # Include default auth urls
    
    # The login page’s pattern matches the URL http://localhost:8000/users
    # /login/. When Django reads this URL, the word users tells Django to look in
    # users/urls.py, and login tells it to send requests to Django’s default login view.
    path("", include("django.contrib.auth.urls")),
    
    # Registration page
    path("register/", views.register, name="register")
]

learningLogs/forms.py
from django import forms

from .models import Topic, Entry

# The topic ModelForm
# Any page that lets a user enter and submit information on a web page is a form, even if it doesn't look like one. When users enter info, we need to validate that the info provided is the right kind of data and is not malicious (code that breaks our server). We then need to process and save valid info to the appropriate place in the db.
# The simplest way to build a form in django is to use a 'ModelForm' which uses the info from the models we defined in models.py to automatically build a form.

# We import the forms modules and the model we'll work with, called Topic at the top
# Below we define a class which inherits from forms.ModelForm
class TopicForm(forms.ModelForm):
    # The simplest version of a ModelForm consists of a nested Meta class telling django which model to base the form on and which fields to include int he form
    class Meta:
        # Here we build a form from the Topic model and include only the text field below model =
        model = Topic
        fields = ["text"]
        # Here we tell django not to generate a label for the text field
        labels = {"text": ""}
        
# On to urls.py

# The entry ModelForm
# We need to create a form associated with the Entry model but this time wiht a bit more customization than TopicForm

# We first import the class Entry from models.py
class EntryForm(forms.ModelForm):
    
    class Meta:
        # Everything is the same below as TopicForm
        model = Entry
        fields = ["text"]
        labels = {"text": ""}
        # A widget attribute is an HTML form element, such as a single-line text box, multi-line text area, or drop-down list.
        # By including the widgets attribute, we can override django's default widget choices. By telling django to use a forms.Textarea element, we're customizing the input widget for the first 'text' so the text area will be 80 columns wide instead of the default 40.
        widgets = {"text": forms.Textarea(attrs={"cols": 80})}

# Back to urls.py

learningLogs/views.py
from django.shortcuts import render, redirect
# Django makes it easy to restrict access to certain pages to logged-in users through the @login_required decorator. A decorator is a directive placed just before a function definition that python applies to the function before it runs, to alter how the function code behaves.
from django.contrib.auth.decorators import login_required
# A 404 response is a standard error response that's returned when a requested resource doesn't exist on a server. We import Http404 which we'll raise if the user requests a topic they shoudn't see.
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Writing a view
# A view function takes in information from a request, prepares the data needed to generate a page, and then sends the data back to the browers, often by using a template that defines what the page will look like.

# The import of render function at the top renders the response based on the data provided by views.

# When a URL request matches the pattern we just defined, django looks for a function called index() in the views.py file. Django then passes the request object to this view function. With no data needing to be processed we call the render() function.
# The render() function passes two arguments. The original request object and a template it can use to build the page. The template will be in index.html
def index(request):
    """The home page for Learning Log"""
    return render(request, "learningLogs/index.html")

# Topics page
# We added topics to our urls.py so we can access by going to /topics in the url.
# We now need to write the topics function to retrieve data from the database and send it to the template.

# We first need to import the model associated with the data we need at the top.
# The topics() function needs one parameter, the request object django received from the server


# We apply login_required() as a decorator to the topics() view function by prepending 
# login_required with the @ symbol. As a result, Python knows to run the code in login_required()
# before the code in topics(). 
# The code in login_required() checks whether a user is logged in, and
# Django runs the code in topics() only if they are. If the user isn’t logged in,
# they’re redirected to the login page.
# To make this redirect work, we need to modify settings.py so Django knows where to find the login page. Add LOGIN_URL = 'users:login' to the very end of settings.py
# After adding the above to settings.py, when an unauthenticated user request a pages protected by the @login_required decorator, django will send the user to the URL defined by LOGIN_URL in settings.py
@login_required
def topics(request):
    """Show all topics"""
    
    # We query the database by asking for the Topic objects, sorted by the dateAdded attribute. We store the resulting queryset in topics var.
    # Currently if we're logged in, we'll be able to see all the topics, no matter which user we're logged in as. We need to update topics below to only show the topics that belong to them.
    # When a user is logged in, the request object has a request.user attribute set that stores info about the user. The query Topic.objects.filter... tells django to retrive only the Topic objects from the database whose owner attribute matches the current user. Because we're not changing how the topics are displayed, we don't need to change the template for the topics page at all.
    topics = Topic.objects.filter(owner=request.user).order_by("dateAdded")
    # We define a context that we'll send to the template. A context is a dictionary in which the keys are names we'll use in the template to access the data, and the values are the data we need to send to the template.
    context = {"topics": topics}
    # When building a page that uses data, we pass the context variable to render() as well as the request object and the path to the template
    return render(request, "learningLogs/topics.html", context)

# The topic view
# The topic() function needs to get the topic and all associated entries from the database

# This is the first view function that requires a param other than the request object. The function accepts the value captured by the expression /<int:topic_id>/ and stores it in topicId
@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries"""
    # We use get() to retrieve the topic, just as we did in the django shell.
    topic = Topic.objects.get(id=topic_id)
    # We get the entries associated with this topic, and we order them according to dateAdded. The minus sign sorts the results in reverse order, the most recent entries first.
    
    # Make sure the topic belongs to the current user.
    # After receiving a topic request, we make sure the topic's user matches the currently logged in user before rendering the page. If the current user doesn't own the requested topic, we raise the Http404 exception and django returns a 404 error page.
    if topic.owner != request.user:
        raise Http404
    
    # of note, in lesson they have topic_set, the topic is the lower case of the second model (class Topic), the one that holds the topics themselves.
    entries = topic.entry_set.order_by("-dateAdded")
    # We store the topic and entries in the context dictionary and send context to the template topic.html
    context = {
        "topic": topic, 
        "entries": entries
        }
    return render(request, "learningLogs/topic.html", context)

# The newTopic() view function 
# As the top we need to import TopicForm from forms.py much like we did with models for our topics. We also import redirect which we use to redirect the user back to the topics page after they submit their topic.


# We use GET requests for pages that only read data from the server. We usually use POST requests 
# when the user needs to submit information through a form.
@login_required
def newTopic(request):
    """Add a new topic"""
    
    # The test below determines whether the request method is GET or POST. It the request method isn't POST, the request is probably GET, so we need to return a blank form (if it's another type of request, a blank form is safe to return).
    if request.method != "POST":
        # No data submitted; create a blank form
        # We make an instance of TopicForm, assign it to a variable, and send the form to the template in the context dictionary at the bottom. Because we didn't include any arguments, django creates a blank form that users can fill out.
        form = TopicForm()
    # If the request method is POST, the else block will run and process the data submitted in the form.
    else:
        # POST data submitted; process data
        
        # We make an instance of TopicForm and pass it the data entered by the user, stored in request.POST. The form object that's returned contains the info submitted by the user.
        form = TopicForm(data=request.POST)
        # We can't save the submitted info in the db until we've checked that it is valid.
        # is_valid() checks that all fields types are filled in (by default all fields must be filled) and that the data entered matches the field types expected (i.e. 200 character limit of CharField)
        if form.is_valid():
            # Currently our page for adding topics is broken because it doesn't associate a new topic with any particular user. It generates a NOT NULL error.
            
            # We call form.save() with the commit=False argument because we need to modify the new topic before saving it to the db.
            newTopic = form.save(commit=False)
            # We then set the new topic's owner attribute to the current user
            newTopic.owner = request.user
            # Finally, we call save() on the topic instance we just defined.
            newTopic.save()
            
            
            # If everything validates, we save the data to the db
            # form.save()
            # Now saved, we can leave the page so we redirect the user back to the topics page
            return redirect("learningLogs:topics")
        
    # Display a blank or invalid form
    

    # The context variable is defined at the end of the view function, and the page is rendered
    # using the template newTopic.html. This code is placed outside of any if block; it will run if
    # a blank form was created, and it will run if a submitted form is determined to be invalid.
    context = {"form": form}
    return render(request, "learningLogs/newTopic.html", context)

# We need to import our EntryForm at the top from forms.py
# The definition of newEntry() has a topic_id param to store the value it receives from the URL


@login_required
def newEntry(request, topic_id):
    """Add a new entry for a particular topic"""
    
    # We'll need the topic to render the page and process the form's data, so we us topic_id to get the correct topic
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    
    # We check whether the request method is POST or GET. The if block executes if it's a GET request, and we create a blank instance of EntryForm.
    if request.method != "POST":
        # No data submitted; create a blank form
        form = EntryForm()
    else:
        # POST data submitted; process data
        
        # If POST we process the data by making an instance of EntryForm populated with the POST data from the request object
        form = EntryForm(data=request.POST)
        
        # checking if form is valid
        if form.is_valid():
            # If it is, we save it to the db. The commit=False tells django to create a new entry object and assign it to newEntry without saving it the database yet.
            newEntry = form.save(commit=False)

learningLogs/templates/learningLogs/base.html
{% load bootstrap4 %}
{% comment %} Above we load the collection of template tags available in django-bootstrap4 {% endcomment %}

{% comment %} Below we are decalring this file as an HTML document written in english {% endcomment %}
<!DOCTYPE html>
<html lang="en">
{% comment %} The head of an HTML file doesn't contain any content, it just tells the browser what it needs to know to display the page correctly. {% endcomment %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% comment %} Here we add a title to name the page when we load the page in our browser (shows in tab, or title bar) {% endcomment %}
    <title>Learning Log</title>

    {% comment %} Here we are using one of bootstrap4's custom tamplate tags which tells django to include all the bootstrap style files. The tag that follows enables all the intereactive behaviour you might use on a page, such as collapsible navigation bars. {% endcomment %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery="full" %}
</head>
<!-- Body tag contains the content users will see on page -->
<body>
    <!-- nav tag indicates the page's navigation links section -->
    <!-- Everything within the tags is styled according to the bootstrap style rules defined by the selectors navbar, navbar-expand-md, etc. A selector determines which elements on a page a certain style rule applies to. -->
    <!-- mb is margin bottom -->
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <!-- Create a link to our homepage which will appear on every page. -->
        <a href="{% url 'learningLogs:index' %}" class="navbar-brand">Learning Log</a>

        <!-- Here we are defining a button that appears if the browser window is too narrow to display the whole navigation bar horizontally. When the user clocks the buttom, the navigation elements will appear in a drop-down list. The collapse reference causes the navigation bar to collapse when the user shrinks the browser window or when the site is displayed on mobile devices with small screens. -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Opening a new section of the navbar using a div. This is the beginning of the part of the navbar that will be collapsed on narrow screens and windows. -->
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <!-- We define a new set of links. Bootstrap defines navigation elements
            as items in an unordered list with style rules that make it look nothing
            like a list. -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="{% url 'learningLogs:topics' %}" class="nav-link">Topics</a>
                </li>
            </ul>
            <!-- Beginning a new set of links by using another ul tag. -->
            <!-- ml-auto is short for margin-left-automatic. This pushes the links to the right side of the screen -->
            <ul class="navbar-nav ml-auto">
                <!-- We create an if block to display the links conditionally, based on whether the user is logged in or not. -->
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <!-- The span element styles pieces of text, or elements of a page that are part of a longer line -->
                    <span class="navbar-text">Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a href="{% url 'users:logout' %}" class="nav-link">Log out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'users:register' %}" class="nav-link">Register</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'users:login' %}" class="nav-link">Log in</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!-- Main tag it used for the most significant part of the body of a page -->
    <!-- Container is a bootstrap way to group elements on a page. -->
    <main class="container" role="main">
        <!-- pb is padding bottom, mb is margin bottom -->
        <div class="pb-2 mb-2 border-bottom">
            <!-- The page header block will be used to title most of our pages -->
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
    
</body>
</html>

<!-- Template inheritance -->
<!-- When building a website, some elements will always need to be repeated on 
each page. Rather than writing these elements directly into each page, you can 
write a bse template containing the repeated elements and then have each page 
inherit from the base. -->

<!-- The parent template -->
<!-- This file will contain elements common to all pages; every other template
will inherit from base.html. The only element we want to repeat on each
page right now is the title at the top. Because we’ll include this template on
every page, let’s make the title a link to the home page -->


<!-- The first part of this file creates a paragraph containing the name of
the project, which also acts as a home page link. To generate a link, we use
a template tag, which is indicated by braces and percent signs. A template
tag generates information to be displayed on a page. Our template tag
% url 'learningLogs:index' % generates a URL matching the URL pattern
defined in learningLogs/urls.py with the name 'index' -->
<!-- In this example, learning_logs is the namespace and index is a uniquely 
named URL pattern in that namespace. The namespace comes from the value we assigned 
to appName in the learningLogs/urls.py file. -->
<!-- Having the template tag generate the URL for us makes it much easier
to keep our links up to date. We only need to change the URL pattern in
urls.py, and Django will automatically insert the updated URL the next time
the page is requested. Every page in our project will inherit from base.html,
so from now on, every page will have a link back to the home page. -->
{% comment %} <p> {% endcomment %}
    {% comment %} <a href="{% url "learningLogs:index" %}">Learning Log</a> - {% endcomment %}
    {% comment %} <a href="{% url "learningLogs:topics" %}">Topics</a> - {% endcomment %}
    {% comment %} Addding a login link that only shows if user isn't logged in {% endcomment %}

    {% comment %} In Django’s authentication system, every template has a user variable
    available, which always has an is_authenticated attribute set: the attribute is
    True if the user is logged in and False if they aren’t. {% endcomment %}

    {% comment %} Here we display a greeting if the user is logged in. Authenticated users have an additional 'username' attribute set, which we use to personalize the greeting and remind the user they're logged in. {% endcomment %}
    {% comment %} {% if user.is_authenticated %} {% endcomment %}
        {% comment %} Hello, {{ user.username }}. {% endcomment %}
        {% comment %} Log out button under user auth portion so only they can see it {% endcomment %}
        {% comment %} <a href="{% url 'users:logout' %}">Log out</a> {% endcomment %}
    {% comment %} {% else %} {% endcomment %}
        {% comment %} Link to registration page {% endcomment %}
        {% comment %} <a href="{% url 'users:register' %}">Register</a> - {% endcomment %}
        {% comment %} Here we display a link to the login page for uesrs who haven't been authenticated {% endcomment %}
        {% comment %} <a href="{% url 'users:login' %}">Log in</a> {% endcomment %}
    {% comment %} {% endif %} {% endcomment %}
{% comment %} </p> {% endcomment %}

<!-- The below are called block tags. This block, names content, is a placeholder. The child template will define the kind of info that goes in the content block. -->
<!-- A child template doesn't have to define every block from its parent, so you can reserve space in parent templates for as many blocks as you like. The child template uses only as many as it requires -->
{% comment %} {% block content %}{% endblock content %} {% endcomment %}

<!-- On to index.html to update the child template -->

learningLogs/templates/learningLogs/editEntry.html
{% extends "learningLogs/base.html" %}

{% block content %}
    <p><a href="{% url 'learningLogs:topic' topic.id %}">{{ topic }}</a></p>

    <p>Edit entry:</p>

    {% comment %} The action argument send the form back to the editEntry() function for processing. We include the entry ID as an argument in the url tag, so the view function can modify the correct entry object. {% endcomment %}
    <form action="{% url 'learningLogs:editEntry' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>
    {% comment %} On to topic.html to link to this page {% endcomment %}

{% endblock content %}

learningLogs/templates/learningLogs/newEntry.html
{% extends "learningLogs/base.html" %}

{% block content %}

    {% comment %} We show the topic at the top of the page so the user can see which topic they're adding an entry to. The topic also acts as a link back to the main page for that topic {% endcomment %}
    <p><a href="{% url 'learningLogs:topic' topic.id %}">{{ topic }}</a></p>

    <p>Add a new entry:</p>
    {% comment %} The form's action argument includes the topic_id value in the URL, so the view function can ssociate the new entry with the correct topic. {% endcomment %}
    <form action="{% url 'learningLogs:newEntry' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add entry</button>
    </form>

{% comment %} Off to topic.html to link to the newEntry page {% endcomment %}

{% endblock content %}

learningLogs/templates/learningLogs/newTopic.html
{% extends "learningLogs/base.html" %}

{% block content %}

    <p>Add a new topic:</p>
    {% comment %} We define an HTML form. The action argument tells the browser where to send the data submitted in the form. In this case, we send it back to the view function newTopic(). The method argument tells the browser to submit the data as a POST request{% endcomment %}
    <form action="{% url 'learningLogs:newTopic' %}" method="post">
        {% comment %} The template tag below is used by django to prevent attackers from using the form to gain unauthorized access to the server. {% endcomment %}
        {% csrf_token %}
        {% comment %} Here we display the form. Django makes it simple by only needed us to include the template variable for django to create all the necessary fields. The as_p` modifier tells django to render all the form elements in paragraph format.{% endcomment %}
        {{ form.as_p }}
        {% comment %} Django doesn't create a submit button for forms so we need to.{% endcomment %}
        <button name="submit">Add topic</button>
    </form>

    {% comment %} On to topics.html to link newtopic to topics {% endcomment %}

{% endblock content %}

learningLogs/templates/learningLogs/topic.html
<!-- We extend base.html as we do for all pages in the project -->
{% extends "learningLogs/base.html" %}

{% comment %} We place the topic in the page_header block {% endcomment %}
{% block page_header %}
    <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
    <p>
        <a href="{% url 'learningLogs:newEntry' topic.id %}">Add new entry</a>
    </p>

    {% for entry in entries %}
        {% comment %} Previously we used ul to structure our topics. We changed it by giving each topic a div element with the selector 'card'. This card has two nested elements. One to to hold the timestamp and the link to edit the entry, and another to hold the body of the enty {% endcomment %}
        <div class="card mb-3">
            {% comment %} We created a header element with the selector card-header. This card header contains the date the entrywas made and a link to edit it. {% endcomment %}
            <h4 class="card-header">
                {{ entry.dateAdded|date:"M d, Y H:i" }}
                {% comment %} The small tag makes it appear a little smaller than the timestamp {% endcomment %}
                <small>
                    <a href="{% url 'learningLogs:editEntry' entry.id %}">edit entry</a>
                </small>
            </h4>
            {% comment %} The div with card-body places the text of the entry in a somple box on the card. {% endcomment %}
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>There are no entries for this topic yet.</p>
    {% endfor %}

{% endblock content %}










{% comment %} {% block content %} {% endcomment %}

    <!-- Showing the topic that's currently being displayed which is stored in the template variable topic. The variable topic is available because it's included in the context dictionary -->
    {% comment %} <p>Topic: {{ topic }}</p> {% endcomment %}

    {% comment %} <p>Entries:</p> {% endcomment %}
    {% comment %} <p> {% endcomment %}
        {% comment %} <a href="{% url 'learningLogs:newEntry' topic.id %}">Add new entry</a> {% endcomment %}
        {% comment %} On to urls.py to edit entries {% endcomment %}
    {% comment %} </p>
    <ul>
    {% for entry in entries %}
        <li> {% endcomment %}
            <!-- We display the value of the attribute dateAdded. The vertical line represents a template filter, a function that modifies the value in a template variable. -->
            <!-- The filter date show jan 1, 20xx xx:xx -->
            {% comment %} <p>{{ entry.dateAdded|date:"M d, Y H:i" }}</p> {% endcomment %}
            <!-- Displaying the full value of 'text' rather than just the first 50 characters from entry --> 
            <!-- The filter linebreaks ensures that long text entries include line breaks in a format understoof by browsers rather than showing a block on uninterrupted text -->
            {% comment %} <p>{{ entry.text|linebreaks }} </p>
            <p>
                <a href="{% url 'learningLogs:editEntry' entry.id %}">Edit entry</a>
            </p>
        </li> {% endcomment %}
    <!-- We use the empty template again to print a msg to the user when no entries have been made -->
    {% comment %} {% empty %}
        <li>There are no entries for this topic yet.</li>
    {% endfor %}
    </ul> {% endcomment %}

{% comment %} {% endblock content %} {% endcomment %}